tailwind.config = {
      darkMode: "class",
      theme: {
        extend: {
          colors: {
            "on-secondary-container": "#27308a",
            "on-secondary": "#ffffff",
            "surface-container-lowest": "#ffffff",
            "tertiary": "#003b44",
            "tertiary-fixed": "#a1efff",
            "tertiary-container": "#005460",
            "error-container": "#ffdad6",
            "on-secondary-fixed": "#000767",
            "surface-variant": "#e1e3e4",
            "surface-tint": "#255dad",
            "secondary-fixed": "#e0e0ff",
            "on-error-container": "#93000a",
            "on-primary-fixed-variant": "#00458f",
            "background": "#f8f9fa",
            "secondary-container": "#959efd",
            "surface-container-low": "#f3f4f5",
            "on-surface-variant": "#424751",
            "outline": "#737783",
            "primary-fixed": "#d7e2ff",
            "primary": "#00346f",
            "secondary-fixed-dim": "#bdc2ff",
            "tertiary-fixed-dim": "#44d8f1",
            "inverse-on-surface": "#f0f1f2",
            "secondary": "#4c56af",
            "outline-variant": "#c2c6d3",
            "on-primary-container": "#9bbdff",
            "on-error": "#ffffff",
            "surface-dim": "#d9dadb",
            "on-secondary-fixed-variant": "#343d96",
            "surface-container": "#edeeef",
            "inverse-primary": "#abc7ff",
            "inverse-surface": "#2e3132",
            "surface-bright": "#f8f9fa",
            "on-tertiary": "#ffffff",
            "on-primary": "#ffffff",
            "primary-fixed-dim": "#abc7ff",
            "surface-container-highest": "#e1e3e4",
            "on-tertiary-fixed-variant": "#004e59",
            "on-tertiary-fixed": "#001f25",
            "on-tertiary-container": "#34cee6",
            "error": "#ba1a1a",
            "primary-container": "#004a99",
            "on-primary-fixed": "#001b3f",
            "on-background": "#191c1d",
            "surface": "#f8f9fa",
            "surface-container-high": "#e7e8e9",
            "on-surface": "#191c1d"
          },
          fontFamily: {
            "headline": ["Manrope"],
            "body": ["Inter"],
            "label": ["Inter"]
          },
          borderRadius: {
            DEFAULT: "0.125rem",
            lg: "0.25rem",
            xl: "0.5rem",
            full: "0.75rem"
          },
        },
      },
    }